// jev-loop — the field ledger. Add a lesson = add an object. Keep evidence measured, name who paid for it.
// group: judging | acting | reading | voice | shipping
window.JEV_LESSONS = [
  {slug:"belief-is-not-a-finding", group:"judging",
   lesson:"A candidate bug is not a finding until a second session with no memory has tried to disprove it.",
   evidence:"A single long-lived agent that tests and then checks its own work agrees with itself. Only survivors of the verifier reach a human.",
   source:"qa-agent design notes", url:"https://github.com/msilvera-howdy/qa-agent"},
  {slug:"broken-vs-could-not-test", group:"judging",
   lesson:"\"Broken\" and \"I could not test it\" are opposite verdicts. A run that never reached the app publishes nothing.",
   evidence:"Verdicts merge pessimistically: completed, blocked by login, blocked by environment, data gap, timeout. Reporting no defects after a blocked run is the most expensive lie a tester can tell.",
   source:"qa-agent design notes", url:"https://github.com/msilvera-howdy/qa-agent"},
  {slug:"one-question-one-dimension", group:"judging",
   lesson:"Each question judges one dimension. Overlapping options spread probability and confidence collapses.",
   evidence:"Our first composer-state question mixed \"empty box\" with \"agent running\"; Jev answered at 0.27 confidence and was wrong twice in three. Split into two questions: four for four at 0.93 to 0.99.",
   source:"our pane-state reader, 2026-09-21", url:"#"},
  {slug:"low-confidence-is-the-model-working", group:"judging",
   lesson:"A low confidence is the model telling you the question is bad or the state is thin. Fix the question before adding a threshold.",
   evidence:"Confidence is derived from the shape of the distribution, not the winning probability. A winner at 0.67 came back with confidence 0.59 on a real two-way split.",
   source:"TypeSafe docs on confidence, our live runs", url:"https://docs.typesafe.ai/confidence"},
  {slug:"structured-diffs-move-recall", group:"judging",
   lesson:"Feed the judge a structured before-and-after diff, not a raw page.",
   evidence:"Across 15 versions and about 80 benchmark runs, only two changes moved recall on the holdout: structured diffs for the judge, and the absence path.",
   source:"jevqa benchmark", url:"https://github.com/Todmy/jevqa/blob/main/BENCHMARK.md"},
  {slug:"absence-path", group:"judging",
   lesson:"A control the spec names that appears on no screen is a finding. It is the most reliable finding there is.",
   evidence:"Missing or unreachable features were half of everything jevqa found and the half most often confirmed.",
   source:"jevqa", url:"https://github.com/Todmy/jevqa"},
  {slug:"holdout-or-it-did-not-happen", group:"judging",
   lesson:"Judge every mechanism on a split it was not tuned on.",
   evidence:"Eight per-bug oracles tuned on apps 1 to 10 gained three to five bugs there and zero on the holdout.",
   source:"jevqa benchmark", url:"https://github.com/Todmy/jevqa/blob/main/BENCHMARK.md"},
  {slug:"ceiling-is-on-the-action-side", group:"acting",
   lesson:"When recall stalls near 20 percent, the actor is the limit, not the judge. More personas and journeys move it; more oracle tuning does not.",
   evidence:"jevqa and a Claude Opus plus Playwright agent hit the same ceiling on the same apps. Oracle prompt tuning, triage, form filling, widget drivers and triple sampling gave no measurable gain.",
   source:"jevqa benchmark", url:"https://github.com/Todmy/jevqa/blob/main/BENCHMARK.md"},
  {slug:"select-never-generate", group:"acting",
   lesson:"Code cuts the candidate values; the model picks one; code copies it verbatim.",
   evidence:"Voice-driven browser control extracts URLs, queries and typed text as spans with regexes, then asks Jev which span is the payload. No hallucinated text can reach the page.",
   source:"jev-voice-browser", url:"https://github.com/moritzkremb/jev-voice-browser"},
  {slug:"fan-out-then-decide-in-code", group:"acting",
   lesson:"Ask every question you might need in one request, including speculative ones, and let code ignore the irrelevant answers.",
   evidence:"Questions run in parallel, so adding them barely changes latency. Twelve questions per spoken partial return in about 300 ms.",
   source:"TypeSafe fan-out pattern, jev-voice-browser", url:"https://docs.typesafe.ai/patterns/fan-out"},
  {slug:"guardrail-destructive-clicks", group:"acting",
   lesson:"Ask \"would this delete, send, or pay\" before every click. Low confidence can never stay allow; it promotes to review.",
   evidence:"Destructive clicks in the voice browser wait for a spoken confirm. The Playwright harness maps two yes-or-no questions to allow, review or block.",
   source:"qa-ai-harness, jev-voice-browser", url:"https://github.com/SRodriguezBottero/qa-ai-harness"},
  {slug:"memory-lives-in-the-state", group:"acting",
   lesson:"The model has no memory between calls. Put the last few actions and their outcomes in the state so corrections like \"no, the other one\" resolve.",
   evidence:"Three recent actions with what was said, what was done and what happened made \"go back to the results\" and \"not that one\" work without any session on the model side.",
   source:"jev-voice-browser", url:"https://github.com/moritzkremb/jev-voice-browser"},
  {slug:"rule-first-model-second", group:"reading",
   lesson:"When a deterministic signal exists, it stays the primary reader. The model is the second reader for the cases the rule cannot see.",
   evidence:"Whether terminal text is a ghost suggestion is a rendering attribute. The attribute rule is exact and free; Jev reads the tagged text and agreed 30 of 30 times live, which is what makes it useful across three different terminal UIs.",
   source:"our pane-state reader, 2026-09-21", url:"#"},
  {slug:"text-only-judge-vision-on-escalation", group:"reading",
   lesson:"Jev sees text, not pixels. Judge the textual substrate on every page and send only the flagged few to a vision model.",
   evidence:"A crawler triages console errors, failed requests and page text with one Jev call per page, then spends vision tokens only on what Jev flagged. Most of a crawl costs near zero.",
   source:"web-qa-jev-agent", url:"https://github.com/Clawbuilders/web-qa-jev-agent"},
  {slug:"stale-screen-needs-a-key", group:"reading",
   lesson:"A screen can show old bytes until a key is pressed. No reader, rule or model, can fix that; the protocol can.",
   evidence:"A nudge into an idle agent failed three ways in a row because the composer showed a stale suggestion. One printable key and a backspace before reading solved it.",
   source:"our fleet, 2026-09-21", url:"#"},
  {slug:"transcribe-locally-decide-remotely", group:"voice",
   lesson:"Speech stays on the device; only the transcript goes to the model. Decide on every partial, act when the words commit.",
   evidence:"Browser speech or on-device whisper plus one Jev call per partial: last word to decision about 300 ms including a 200 ms debounce. Closed-set commands act before the sentence ends; free text waits for the final result.",
   source:"jev-voice-browser, jev-voice, jev-voice-control", url:"https://github.com/moritzkremb/jev-voice-browser"},
  {slug:"do-not-use-it-where-a-rule-fits", group:"shipping",
   lesson:"If a pattern-matcher or a plain question gets 32 of 32 at zero latency, the decision model does not belong on that screen.",
   evidence:"Name capture during onboarding: a regex and Jev both scored 32 of 32 on fixtures. The screen promises no API key, so a network hop bought nothing. The right owner turned out to be the conversation brain that already holds the chat.",
   source:"our onboarding review, 2026-09-22", url:"#"},
  {slug:"pin-the-version-log-the-served-one", group:"shipping",
   lesson:"Aliases move. Pin the version once thresholds are tuned, and log the served version with every answer.",
   evidence:"The response reports the version that answered, not the alias you sent. Thresholds tuned on one version are not a promise on the next.",
   source:"TypeSafe models page", url:"https://docs.typesafe.ai/models"},
  {slug:"redact-before-judging", group:"shipping",
   lesson:"Scrub secrets from console output and page text before any model call or any public report.",
   evidence:"A misconfigured page printing its own API key into an error message must never be quoted in a bug report.",
   source:"web-qa-jev-agent", url:"https://github.com/Clawbuilders/web-qa-jev-agent"},
  {slug:"publish-your-precision", group:"shipping",
   lesson:"Publish the share of findings that are confirmed defects. A tool that hides it is lying.",
   evidence:"About one in eight jevqa findings maps to a confirmed defect. Readers are told to read missing features first and skim the rest in ninety seconds.",
   source:"jevqa", url:"https://github.com/Todmy/jevqa"},
];
window.JEV_NUMBERS = [
  {what:"Bugs found on 20 benchmark apps with 107 known bugs", value:"22%", note:"jevqa v15, 50 actions per app", url:"https://github.com/Todmy/jevqa/blob/main/BENCHMARK.md"},
  {what:"Cost and time per app for that run", value:"$0.29 to $0.41, 5 to 6 min", note:"Claude Opus plus Playwright on the same apps: $3.20 and 17%", url:"https://github.com/Todmy/jevqa/blob/main/BENCHMARK.md"},
  {what:"Findings that are confirmed defects", value:"1 in 8", note:"published by the tool's author", url:"https://github.com/Todmy/jevqa"},
  {what:"Last spoken word to decision", value:"about 300 ms", note:"includes a 200 ms debounce; Jev median about 300 ms", url:"https://github.com/moritzkremb/jev-voice-browser"},
  {what:"One decision call in our stack", value:"about 700 input tokens", note:"three questions over a short record; output is free", url:"#"},
  {what:"Rule versus model agreement reading terminal screens", value:"30 of 30", note:"live captures across three terminal UIs", url:"#"},
  {what:"Context limits per request", value:"64k tokens total, 32k per question", note:"state plus all questions; state plus the longest question", url:"https://docs.typesafe.ai/models"},
];
window.JEV_CHANGELOG = [
  {date:"2026-09-22", text:"Site opened with 20 lessons from four open-source projects, three papers and our own two loops: reading agent terminals and routing voice. Next: run jevqa against our staging build and add what it teaches."},
];
