// jev-loop — the field ledger. Add a lesson = add an object. Keep evidence measured, name who paid for it.
// group: judging | acting | reading | voice | shipping
window.JEV_LESSONS = [
  {slug:"expected-empty-is-not-404", group:"shipping",
   lesson:"An empty state is not an error. Serving 404 for 'nothing here yet' teaches every reader, human or model, that the app is broken on first run.",
   evidence:"Three routes on a fresh install answered 404 for normal emptiness: the chat history list, the memory context layer, and a thread that has not been written yet. Each one produced a fan of http flags and a 'Failed to load' message a first-run user sees before they have done anything.",
   source:"our calibrated red-team run, 2026-09-22", url:"#"},
  {slug:"auto-found-is-a-check-that-cannot-fail", group:"judging",
   lesson:"A recall table that marks 'found' whenever any flag fired on the mapped journey cannot fail. Require the finding text to name the bug's control or effect.",
   evidence:"The generated table over-counted; a hand pass over the same runs landed at found 4, missed 2, not reachable 7 of 13, and named why for every row.",
   source:"our calibrated red-team run, 2026-09-22", url:"#"},
  {slug:"the-actor-is-the-cost-line", group:"acting",
   lesson:"With a decision model as the judge, the persona actor is where the money goes. Budget the actor, not the judge.",
   evidence:"A full three-persona run cost $4 to $5.50, almost all of it the Sonnet actor at about 2k tokens per step. Jev for the same run was about half a cent. A smaller actor model cuts the bill roughly ten times and is one environment variable.",
   source:"our calibrated red-team run, 2026-09-22", url:"#"},
  {slug:"unreachable-rows-name-the-missing-device", group:"acting",
   lesson:"When a known bug is not reachable, say which capability the harness lacks. The list of missing devices is the build plan.",
   evidence:"Five of seven unreachable rows needed a microphone; one needed a chat window instead of a page; one needed a parity question that did not exist. Fake-mic flags, a parity oracle, and four success-check fixes became the next three changes.",
   source:"our calibrated red-team run, 2026-09-22", url:"#"},
  {slug:"icon-only-controls-are-invisible", group:"reading",
   lesson:"A control with only an icon and a hover tooltip does not exist for any reader that is not a hovering human. Testers, screen readers and the model all see an unnamed button.",
   evidence:"The agent card's open-chat button is a maximize icon with a title attribute. In 18 visits to the agents page the tester never opened a chat; it clicked Menu, Kill and the assistant box instead. Shaw spotted it from the behaviour before we read the code.",
   source:"our headed run on staging, 2026-09-22", url:"#"},
  {slug:"a-flat-planner-drifts", group:"acting",
   lesson:"A planner that asks only 'which control next' with the whole spec as the goal drifts between pages. It needs to know which step of which journey it is on and what its last action changed.",
   evidence:"Eighty steps, thirty screens, sixteen random side-steps, zero completed journeys. Every choice on the agents page landed between 0.06 and 0.39 confidence. The report was still useful: the oracle side found a real unmounted route.",
   source:"our headed run on staging, 2026-09-22", url:"#"},
  {slug:"one-broken-route-fans-out", group:"judging",
   lesson:"One failing request can flag a dozen unrelated steps when the page polls it. Group http flags by the failing URL before reading them as separate bugs.",
   evidence:"Twelve http_error flags across five pages traced to one unmounted API route that the chat-history page polls. Replaying the actual actions on those pages returned 200.",
   source:"our headed run on staging, 2026-09-22", url:"#"},
  {slug:"watch-one-run-headed", group:"shipping",
   lesson:"Watch at least one run with your own eyes. The person who knows the product reads the tester's confusion faster than any report does.",
   evidence:"Shaw watched the run from his Mac and asked why it kept refreshing and typing digits. That question led straight to the undiscoverable open-chat button and the missing create-agent control, neither of which the report named.",
   source:"our headed run on staging, 2026-09-22", url:"#"},
  {slug:"dictation-journey-needs-two-browsers", group:"acting",
   lesson:"A dictation journey is two journeys: one per speech path. Test the browser-native path and the record-then-transcribe path separately, on the browsers that use each.",
   evidence:"Our staging build dictates through Web Speech on Chromium and through a recorded clip plus local transcription elsewhere. A headless run has no microphone, so the harness needs a stand-in recogniser for the first path and a fixture clip for the second.",
   source:"gm's routing after the first run, 2026-09-22", url:"#"},
  {slug:"native-dialogs-are-invisible-to-text", group:"reading",
   lesson:"A file picker, a permission prompt, or any native dialog leaves no trace in page text. A text-diff oracle will call the button dead.",
   evidence:"Our first jevqa run flagged Attach a file as ignored on two screens with 0.88 and 0.91 probability. The button works; it opens the OS file chooser, which is invisible to the DOM. The fix is on our side: expose a chip, a status line, or an aria-live message the moment the picker opens, so a user (and a tester) sees the app react.",
   source:"our jevqa run on staging, 2026-09-22", url:"#"},
  {slug:"absence-path-needs-nav-in-the-spec-vocabulary", group:"judging",
   lesson:"The absence path only works when the spec names controls in the words the UI uses. A page reachable through a drawer is not missing, but the tester cannot know that.",
   evidence:"Three of eight findings said Agents, Approvals and Inbox were missing from the home screen. All three exist behind the menu drawer. The spec said 'Agents page'; the home screen shows a menu glyph. Either name the drawer in the spec or expose the nav as text.",
   source:"our jevqa run on staging, 2026-09-22", url:"#"},
  {slug:"a-flag-is-a-place-to-look", group:"judging",
   lesson:"An http_error flag with low oracle probabilities is a network sample, not a verdict. Replay the request yourself before calling it a bug.",
   evidence:"Two flags cited an HTTP error after clicking Ask Arturo and New. The oracle questions on those steps read 0.14 to 0.44. We replayed the same text request against the box and got 200 with a reply. Keep the flag, downgrade it to 'look here'.",
   source:"our jevqa run on staging, 2026-09-22", url:"#"},
  {slug:"the-tester-probes-injection-for-free", group:"acting",
   lesson:"An exploratory tester types script tags and digit strings into every box. Read what your assistant said back; that transcript is a free sanitisation test.",
   evidence:"The run sent a stray script tag and a five-digit string to the assistant. Both landed as plain text and the assistant said so. That is a passing result nobody wrote a test for.",
   source:"our jevqa run on staging, 2026-09-22", url:"#"},
  {slug:"belief-is-not-a-finding", group:"judging",
   lesson:"A candidate bug is not a finding until a second session with no memory has tried to disprove it.",
   evidence:"A single long-lived agent that tests and then checks its own work agrees with itself. Only survivors of the verifier reach a human.",
   source:"qa-agent design notes", url:"https://github.com/msilvera-howdy/qa-agent"},
  {slug:"broken-vs-could-not-test", group:"judging",
   lesson:"\"Broken\" and \"I could not test it\" are opposite verdicts. A run that never reached the app publishes nothing.",
   evidence:"Verdicts merge pessimistically: completed, blocked by login, blocked by environment, data gap, timeout. Reporting no defects after a blocked run is the most expensive lie a tester can tell.",
   source:"qa-agent design notes", url:"https://github.com/msilvera-howdy/qa-agent"},
  {slug:"one-question-one-dimension", group:"judging",
   lesson:"Each question judges one dimension. Overlapping options spread probability and confidence collapses.",
   evidence:"Our first composer-state question mixed \"empty box\" with \"agent running\"; Jev answered at 0.27 confidence and was wrong twice in three. Split into two questions: four for four at 0.93 to 0.99.",
   source:"our pane-state reader, 2026-09-21", url:"#"},
  {slug:"low-confidence-is-the-model-working", group:"judging",
   lesson:"A low confidence is the model telling you the question is bad or the state is thin. Fix the question before adding a threshold.",
   evidence:"Confidence is derived from the shape of the distribution, not the winning probability. A winner at 0.67 came back with confidence 0.59 on a real two-way split.",
   source:"TypeSafe docs on confidence, our live runs", url:"https://docs.typesafe.ai/confidence"},
  {slug:"structured-diffs-move-recall", group:"judging",
   lesson:"Feed the judge a structured before-and-after diff, not a raw page.",
   evidence:"Across 15 versions and about 80 benchmark runs, only two changes moved recall on the holdout: structured diffs for the judge, and the absence path.",
   source:"jevqa benchmark", url:"https://github.com/Todmy/jevqa/blob/main/BENCHMARK.md"},
  {slug:"absence-path", group:"judging",
   lesson:"A control the spec names that appears on no screen is a finding. It is the most reliable finding there is.",
   evidence:"Missing or unreachable features were half of everything jevqa found and the half most often confirmed.",
   source:"jevqa", url:"https://github.com/Todmy/jevqa"},
  {slug:"holdout-or-it-did-not-happen", group:"judging",
   lesson:"Judge every mechanism on a split it was not tuned on.",
   evidence:"Eight per-bug oracles tuned on apps 1 to 10 gained three to five bugs there and zero on the holdout.",
   source:"jevqa benchmark", url:"https://github.com/Todmy/jevqa/blob/main/BENCHMARK.md"},
  {slug:"ceiling-is-on-the-action-side", group:"acting",
   lesson:"When recall stalls near 20 percent, the actor is the limit, not the judge. More personas and journeys move it; more oracle tuning does not.",
   evidence:"jevqa and a Claude Opus plus Playwright agent hit the same ceiling on the same apps. Oracle prompt tuning, triage, form filling, widget drivers and triple sampling gave no measurable gain.",
   source:"jevqa benchmark", url:"https://github.com/Todmy/jevqa/blob/main/BENCHMARK.md"},
  {slug:"select-never-generate", group:"acting",
   lesson:"Code cuts the candidate values; the model picks one; code copies it verbatim.",
   evidence:"Voice-driven browser control extracts URLs, queries and typed text as spans with regexes, then asks Jev which span is the payload. No hallucinated text can reach the page.",
   source:"jev-voice-browser", url:"https://github.com/moritzkremb/jev-voice-browser"},
  {slug:"fan-out-then-decide-in-code", group:"acting",
   lesson:"Ask every question you might need in one request, including speculative ones, and let code ignore the irrelevant answers.",
   evidence:"Questions run in parallel, so adding them barely changes latency. Twelve questions per spoken partial return in about 300 ms.",
   source:"TypeSafe fan-out pattern, jev-voice-browser", url:"https://docs.typesafe.ai/patterns/fan-out"},
  {slug:"guardrail-destructive-clicks", group:"acting",
   lesson:"Ask \"would this delete, send, or pay\" before every click. Low confidence can never stay allow; it promotes to review.",
   evidence:"Destructive clicks in the voice browser wait for a spoken confirm. The Playwright harness maps two yes-or-no questions to allow, review or block.",
   source:"qa-ai-harness, jev-voice-browser", url:"https://github.com/SRodriguezBottero/qa-ai-harness"},
  {slug:"memory-lives-in-the-state", group:"acting",
   lesson:"The model has no memory between calls. Put the last few actions and their outcomes in the state so corrections like \"no, the other one\" resolve.",
   evidence:"Three recent actions with what was said, what was done and what happened made \"go back to the results\" and \"not that one\" work without any session on the model side.",
   source:"jev-voice-browser", url:"https://github.com/moritzkremb/jev-voice-browser"},
  {slug:"rule-first-model-second", group:"reading",
   lesson:"When a deterministic signal exists, it stays the primary reader. The model is the second reader for the cases the rule cannot see.",
   evidence:"Whether terminal text is a ghost suggestion is a rendering attribute. The attribute rule is exact and free; Jev reads the tagged text and agreed 30 of 30 times live, which is what makes it useful across three different terminal UIs.",
   source:"our pane-state reader, 2026-09-21", url:"#"},
  {slug:"text-only-judge-vision-on-escalation", group:"reading",
   lesson:"Jev sees text, not pixels. Judge the textual substrate on every page and send only the flagged few to a vision model.",
   evidence:"A crawler triages console errors, failed requests and page text with one Jev call per page, then spends vision tokens only on what Jev flagged. Most of a crawl costs near zero.",
   source:"web-qa-jev-agent", url:"https://github.com/Clawbuilders/web-qa-jev-agent"},
  {slug:"stale-screen-needs-a-key", group:"reading",
   lesson:"A screen can show old bytes until a key is pressed. No reader, rule or model, can fix that; the protocol can.",
   evidence:"A nudge into an idle agent failed three ways in a row because the composer showed a stale suggestion. One printable key and a backspace before reading solved it.",
   source:"our fleet, 2026-09-21", url:"#"},
  {slug:"transcribe-locally-decide-remotely", group:"voice",
   lesson:"Speech stays on the device; only the transcript goes to the model. Decide on every partial, act when the words commit.",
   evidence:"Browser speech or on-device whisper plus one Jev call per partial: last word to decision about 300 ms including a 200 ms debounce. Closed-set commands act before the sentence ends; free text waits for the final result.",
   source:"jev-voice-browser, jev-voice, jev-voice-control", url:"https://github.com/moritzkremb/jev-voice-browser"},
  {slug:"do-not-use-it-where-a-rule-fits", group:"shipping",
   lesson:"If a pattern-matcher or a plain question gets 32 of 32 at zero latency, the decision model does not belong on that screen.",
   evidence:"Name capture during onboarding: a regex and Jev both scored 32 of 32 on fixtures. The screen promises no API key, so a network hop bought nothing. The right owner turned out to be the conversation brain that already holds the chat.",
   source:"our onboarding review, 2026-09-22", url:"#"},
  {slug:"pin-the-version-log-the-served-one", group:"shipping",
   lesson:"Aliases move. Pin the version once thresholds are tuned, and log the served version with every answer.",
   evidence:"The response reports the version that answered, not the alias you sent. Thresholds tuned on one version are not a promise on the next.",
   source:"TypeSafe models page", url:"https://docs.typesafe.ai/models"},
  {slug:"redact-before-judging", group:"shipping",
   lesson:"Scrub secrets from console output and page text before any model call or any public report.",
   evidence:"A misconfigured page printing its own API key into an error message must never be quoted in a bug report.",
   source:"web-qa-jev-agent", url:"https://github.com/Clawbuilders/web-qa-jev-agent"},
  {slug:"publish-your-precision", group:"shipping",
   lesson:"Publish the share of findings that are confirmed defects. A tool that hides it is lying.",
   evidence:"About one in eight jevqa findings maps to a confirmed defect. Readers are told to read missing features first and skim the rest in ninety seconds.",
   source:"jevqa", url:"https://github.com/Todmy/jevqa"},
];
window.JEV_NUMBERS = [
  {what:"Our first run of jevqa against the OrchestraOS staging build", value:"8 findings, 50 steps, 290 s, $0.50", note:"179 Jev calls, 3 Claude calls; 6 of 28 expectations exercised clean; 0 confirmed defects, 1 UX gap (no visible reaction when the file picker opens)", url:"#"},
  {what:"Bugs found on 20 benchmark apps with 107 known bugs", value:"22%", note:"jevqa v15, 50 actions per app", url:"https://github.com/Todmy/jevqa/blob/main/BENCHMARK.md"},
  {what:"Cost and time per app for that run", value:"$0.29 to $0.41, 5 to 6 min", note:"Claude Opus plus Playwright on the same apps: $3.20 and 17%", url:"https://github.com/Todmy/jevqa/blob/main/BENCHMARK.md"},
  {what:"Findings that are confirmed defects", value:"1 in 8", note:"published by the tool's author", url:"https://github.com/Todmy/jevqa"},
  {what:"Last spoken word to decision", value:"about 300 ms", note:"includes a 200 ms debounce; Jev median about 300 ms", url:"https://github.com/moritzkremb/jev-voice-browser"},
  {what:"One decision call in our stack", value:"about 700 input tokens", note:"three questions over a short record; output is free", url:"#"},
  {what:"Rule versus model agreement reading terminal screens", value:"30 of 30", note:"live captures across three terminal UIs", url:"#"},
  {what:"Context limits per request", value:"64k tokens total, 32k per question", note:"state plus all questions; state plus the longest question", url:"https://docs.typesafe.ai/models"},
];
window.JEV_CHANGELOG = [
  {date:"2026-09-22", text:"First calibrated red-team run with personas: found 4, missed 2, unreachable 7 of 13 known bugs, hand-judged. Four lessons: expected-empty is not 404, auto-found cannot fail, the actor is the cost line, unreachable rows name the missing device."},
  {date:"2026-09-22", text:"Headed run on a Mac, watched live. Four lessons: icon-only controls are invisible, a flat planner drifts, one broken route fans out into many flags, and watching one run headed beats reading ten reports."},
  {date:"2026-09-22", text:"First jevqa run against our staging build. Four lessons added from it: native dialogs are invisible to text oracles, the absence path needs nav vocabulary, an http flag is a place to look, and the tester probes injection for free."},
  {date:"2026-09-22", text:"Site opened with 20 lessons from four open-source projects, three papers and our own two loops: reading agent terminals and routing voice. Next: run jevqa against our staging build and add what it teaches."},
];
